### ISSUE TITLE
Bots Shooting

### ISSUE THREAD

**Issue by GangstaPichu** [bmgjet/RECustomBots#1]
Don't know where else to mention this. I notice that the bots when within range they will start shooting. Not necessarily at the player, just wherever they are facing. Doesn't matter if it's a wall or not. They will shoot at it until the player agros them. Just really weird behavior they have. I don't know if that's something that's controlled by the plugin or by rust edit or just how they are? Just thought I'd bring this up incase if it's something un-intended.

**Comment by bmgjet** [comment]
Make sure your on the latest version.
Some bot types in rust edit if they have no navmesh will do as your describing.
Scarecrow type seems to be the best to use if your going to kit them.

If you dont mind sharing your map I can take a look at it on my test server and see if they are acting the same to rule out another plugin overriding there behavour.

**Comment by GangstaPichu** [comment]
> Make sure your on the latest version. Some bot types in rust edit if they have no navmesh will do as your describing. Scarecrow type seems to be the best to use if your going to kit them.
> 
> If you dont mind sharing your map I can take a look at it on my test server and see if they are acting the same to rule out another plugin overriding there behavour.

The navemesh issue is most likely the cause. I have them on a broken down cargo ship and some other monuments. Though, I couldn't get them to move around on the land by some of the monuments. Don't know if they can't be too close to them or what. So, I gave up on trying to make them roam around and move. This is my first time trying to do any of this. Even making this map. 

I'll still send you the map so you can take a look at them in case there's something I might've missed with anything for them.
[Sus Map Vol 2.zip](https://github.com/bmgjet/RECustomBots/files/7738746/Sus.Map.Vol.2.zip)

**Comment by bmgjet** [comment]
Cant reproduce the error your explaining.
Running your map un-edited they behave like normal. Ones with navmesh can move. Ones with out stay on the spot but can still shoot.
Then I tried changing them all out for scarecrows that had a kit on too look like scientist.
They can all move with that bot type. But youll have to play with the height setting other wise there feet are sticking though the ground.

Heres a video.
https://www.youtube.com/watch?v=94Hq7eyrF7Q

**Comment by GangstaPichu** [comment]
> Cant reproduce the error your explaining. Running your map un-edited they behave like normal. Ones with navmesh can move. Ones with out stay on the spot but can still shoot. Then I tried changing them all out for scarecrows that had a kit on too look like scientist. They can all move with that bot type. But youll have to play with the height setting other wise there feet are sticking though the ground.
> 
> Heres a video. https://www.youtube.com/watch?v=94Hq7eyrF7Q

Got the issue fixed, I guess we didn't have the update like I thought we did. That's my bad. Thanks for the help and sorry for the trouble. Kinda feel dumb for making ya go through all that now. I do gotta say though, you make some cool plugins! :)
